version: '3.4'

services:
  monitor:
    image: ${DOCKER_REGISTRY-}monitor
    ports:
        - "8086:80"
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
          cpus: "0.10"
